title = "Sparking Cards"  # From Git
gitRepoUrl = "https://github.com/BoredDynasty/Sparking_Cards" # From Git

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2021 OfficialDynasty. Built with Moonwave and Docusaurus"