syntax = "Luau"
column_width = 110
line_endings = "Windows"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Input"
collapse_simple_statement = "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = true
