--!strict

-- sound-ids.luau

export type SoundData = {
	id: string,
	volume: number,
	speed: number,
}

return {
	Air = {
		id = "rbxassetid://0",
		volume = 0,
		speed = 1.00,
	},
	Asphalt = {
		id = "rbxassetid://133774248698088",
		volume = 0.60,
		speed = 1.00,
	},
	Basalt = {
		id = "rbxassetid://133774248698088",
		volume = 0.60,
		speed = 1.00,
	},
	Brick = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	Carpet = {
		id = "rbxassetid://131412978408311",
		volume = 0.40,
		speed = 1.00,
	},
	Cobblestone = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	Concrete = {
		id = "rbxassetid://133774248698088",
		volume = 0.60,
		speed = 1.00,
	},
	CorrodedMetal = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	CrackedLava = {
		id = "rbxassetid://133774248698088",
		volume = 0.60,
		speed = 1.00,
	},
	DiamondPlate = {
		id = "rbxassetid://133774248698088",
		volume = 0.60,
		speed = 1.00,
	},
	Fabric = {
		id = "rbxassetid://131412978408311",
		volume = 0.40,
		speed = 1.00,
	},
	Foil = {
		id = "rbxassetid://133774248698088",
		volume = 0.60,
		speed = 1.00,
	},
	Forcefield = {
		id = "rbxassetid://329997777",
		volume = 0.60,
		speed = 1.00,
	},
	Glass = {
		id = "rbxassetid://139267724392327",
		volume = 0.60,
		speed = 1.00,
	},
	Granite = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	Grass = {
		id = "rbxassetid://135037154891351",
		volume = 0.60,
		speed = 1.00,
	},
	Glacier = {
		id = "rbxassetid://139267724392327",
		volume = 0.40,
		speed = 1.00,
	},
	Ground = {
		id = "rbxassetid://139406838352611",
		volume = 0.60,
		speed = 1.00,
	},
	Ice = {
		id = "rbxassetid://139267724392327",
		volume = 0.40,
		speed = 1.00,
	},
	Limestone = {
		id = "rbxassetid://140728903346385",
		volume = 0.60,
		speed = 1.00,
	},
	LeafyGrass = {
		id = "rbxassetid://135037154891351",
		volume = 0.60,
		speed = 1.00,
	},
	Marble = {
		id = "rbxassetid://139267724392327",
		volume = 0.60,
		speed = 1.00,
	},
	Metal = {
		id = "rbxassetid://139267724392327",
		volume = 0.60,
		speed = 1.00,
	},
	Mud = {
		id = "rbxassetid://140668467774841",
		volume = 0.60,
		speed = 1.00,
	},
	Neon = {
		id = "rbxassetid://139267724392327",
		volume = 0.60,
		speed = 1.00,
	},
	Pebble = {
		id = "rbxassetid://139267724392327",
		volume = 0.60,
		speed = 1.00,
	},
	Plastic = {
		id = "rbxassetid://135712042029119",
		volume = 0.60,
		speed = 1.40,
	},
	Pavement = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	Rock = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	RoofShingles = {
		id = "rbxassetid://140594308250996",
		volume = 0.60,
		speed = 1.00,
	},
	Rubber = {
		id = "rbxassetid://135712042029119",
		volume = 0.60,
		speed = 1.40,
	},
	Sand = {
		id = "rbxassetid://140668467774841",
		volume = 0.40,
		speed = 1.00,
	},
	Slate = {
		id = "rbxassetid://140668467774841",
		volume = 0.60,
		speed = 1.00,
	},
	Snow = {
		id = "rbxassetid://140668467774841",
		volume = 0.60,
		speed = 1.00,
	},
	Salt = {
		id = "rbxassetid://140668467774841",
		volume = 0.40,
		speed = 1.00,
	},
	Sandstone = {
		id = "rbxassetid://139667774868914",
		volume = 0.60,
		speed = 0.75,
	},
	SmoothPlastic = {
		id = "rbxassetid://14059430825",
		volume = 0.60,
		speed = 1.00,
	},
	Wood = {
		id = "rbxassetid://139932856876296",
		volume = 0.60,
		speed = 1.00,
	},
	WoodPlanks = {
		id = "rbxassetid://140525304232464",
		volume = 0.60,
		speed = 1.00,
	},
}
