--!strict

-- badges.luau

return {
	{
		name = "First Victory",
		description = "Win your first match",
		points = 5,
	},
	{
		name = "Card Collector",
		description = "Collect all card types",
		points = 15,
	},
	{
		name = "The Architect",
		description = "Be in the same server as a Creator.",
		points = 20,
	},
	{
		name = "Out of Bounds",
		description = "Find a way to clip into a place 'unreachable'",
		points = 5,
	},
	{
		name = "L + Ratio",
		description = "Die in the first minute of an active match.",
		points = 5,
	},
	{
		name = "Speedrunner",
		description = "Defeat a top tier player or boss in under 30s.",
		points = 110,
	},
	{
		name = "Please speed!",
		description = "Win a match with under 5% HP remaining.",
		points = 20,
	},
	{
		name = "Public Transport",
		description = "Ride the train.",
		point = 2,
	},
}
