--!strict

-- letterbox.luau

local self = {
	-- letterbox images
	--[[
      https://create.roblox.com/store/asset/110246564937802/3
   ]]
	letterbox_1 = Content.fromAssetId(110246564937802),
	--[[
      https://create.roblox.com/store/asset/81501465181307/4
   ]]
	letterbox_2 = Content.fromAssetId(81501465181307),
}

function self:On()
	-- implementation
end

function self:Off()
	-- implementation
end

return self
