--[[
██████╗░██████╗░░█████╗░███╗░░░███╗██████╗░████████╗  ██████╗░██╗░░░░░██╗░░░██╗░██████╗
██╔══██╗██╔══██╗██╔══██╗████╗░████║██╔══██╗╚══██╔══╝  ██╔══██╗██║░░░░░██║░░░██║██╔════╝
██████╔╝██████╔╝██║░░██║██╔████╔██║██████╔╝░░░██║░░░  ██████╔╝██║░░░░░██║░░░██║╚█████╗░
██╔═══╝░██╔══██╗██║░░██║██║╚██╔╝██║██╔═══╝░░░░██║░░░  ██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗
██║░░░░░██║░░██║╚█████╔╝██║░╚═╝░██║██║░░░░░░░░██║░░░  ██║░░░░░███████╗╚██████╔╝██████╔╝
╚═╝░░░░░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═╝╚═╝░░░░░░░░╚═╝░░░  ╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░

Prompt Plus is a plugin developed by the VortexPortal team.

=======================================
©️2024 VORTEXPORTAL
=======================================
Prompt Plus License

This License Agreement ("Agreement") is entered into by and between VORTEXPORTAL ("Licensor") and the user ("Licensee").

1. License Grant

Licensor grants Licensee a non-exclusive, non-transferable license to use the Roblox Prompt Plugin ("Plugin") solely for personal use within the Roblox platform.

2. Restrictions

Licensee shall not:

    Resell or distribute the Plugin in any form, including but not limited to selling, renting, leasing, sublicensing, or otherwise transferring the Plugin to any third party.
    Modify, reverse engineer, decompile, disassemble, or create derivative works based on the Plugin.
    Use the Plugin for any malicious or illegal purposes, including but not limited to hacking, cheating, or exploiting the Roblox platform or other users.

3. Ownership

The Plugin is the exclusive property of Licensor and is protected by copyright and other intellectual property laws. Licensee acknowledges that they do not acquire any ownership rights in the Plugin.

4. Term and Termination

This Agreement is effective upon Licensee's acceptance and shall remain in effect until terminated. Licensor may terminate this Agreement immediately if Licensee breaches any provision.

5. Disclaimer of Warranty

The Plugin is provided "as is" without any warranties, express or implied. Licensor disclaims all warranties, including but not limited to merchantability, fitness for a particular purpose, and non-infringement.

6. Limitation of Liability

Licensor shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with the use of the Plugin.

7. General

This Agreement constitutes the entire agreement between the parties regarding the Plugin and supersedes all prior or contemporaneous agreements or understandings.

-
VORTEX PORTAL
]]