return {
	["Bronze I"] = {
		["Name"] = "Bronze I",
		["Experience"] = 0,
		["Reward"] = 20,
	},
	["Iron II"] = {
		Name = "Iron II",
		Experience = 1000,
		Reward = 1000,
	},
	["Gold III"] = {
		["Name"] = "Gold II",
		["Experience"] = 2500,
		["Reward"] = 5000,
	},
	["Platinum IV"] = {
		["Name"] = "Platinum IV",
		["Experience"] = 4000,
		["Reward"] = 10000,
	},
	["Emerald V"] = {
		["Name"] = "Emerald V",
		["Experience"] = 5500,
		["Reward"] = 22000,
	},
	["Master VI"] = {
		["Name"] = "Master",
		["Experience"] = 8500,
		["Reward"] = 60000,
	},
	["Elite VII"] = {
		Name = "Elite VII",
		Experience = 10000,
		Reward = 155000,
	},
	["Ruby VIII"] = {
		Name = "Ruby VIII",
		Experience = 15000,
		Reward = 220000,
	},
	["Prismatic IX"] = {
		Name = "Prismatic IX",
		Experience = 225000,
		Reward = 300000,
	},
	["Sparking X"] = {
		["Name"] = "Sparking X",
		["Experience"] = 68000,
		["Reward"] = 650000,
	},
}
