return {
	["Bronze"] = {
		["Name"] = "Bronze",
		["Experience"] = 0,
		["Description"] = "Just starting out!",
		["Reward"] = 20,
	},
	["Gold"] = {
		["Name"] = "Gold",
		["Experience"] = 50000,
		["Description"] = "Going Golden, huh?",
		["Reward"] = 1500,
	},
	["Platinum"] = {
		["Name"] = "Platinum",
		["Experience"] = 100000,
		["Description"] = "You can make jewelry out of this!",
		["Reward"] = 15000,
	},
	["Emerald"] = {
		["Name"] = "Emerald",
		["Experience"] = 200000,
		["Description"] = "A precious gem!",
		["Reward"] = 25000,
	},
	["Master"] = {
		["Name"] = "Master",
		["Experience"] = 350000,
		["Description"] = "You've mastered this one!",
		["Reward"] = 19500,
	},
	["Sparking"] = {
		["Name"] = "Sparking",
		["Experience"] = 100000,
		["Description"] = "Sparking Cards!",
		["Reward"] = 50000,
	},
}
